name: Build YTNoAds
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: false
        default: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTNoAds
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout YTNoAds
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
          path: YTNoAds

      - name: Setup Theos
        uses: ./.github/actions/setup-theos

      - name: Build YTNoAds
        run: |
          cd YTNoAds
          echo "YTNOADS_VERSION=$(grep '^Version:' control | cut -d ' ' -f2)" >> $GITHUB_ENV
          make clean package DEBUG=0 FINALPACKAGE=1
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide
          mv packages/*.deb ${{ github.workspace }}

      - name: Upload the tweak .deb(s)
        uses: actions/upload-artifact@v4
        with:
          name: YTNoAds v${{ env.YTNOADS_VERSION }}
          path: ${{ github.workspace }}/*.deb
          if-no-files-found: error
          overwrite: true

      - name: Create a draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.YTNOADS_VERSION }}
          name: v${{ env.YTNOADS_VERSION }}
          files: ${{ github.workspace }}/*.deb
          draft: true
