name: Build IPA
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O youtube.ipa
          file_type=$(file --mime-type -b youtube.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get YouTube Version
        run: |
          unzip -p youtube.ipa "Payload/YouTube.app/Info.plist" > youtube_info.plist
          echo "YT_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" youtube_info.plist)" >> $GITHUB_ENV

      - name: Checkout YTNoAds
        uses: actions/checkout@v4
        with:
          path: YTNoAds

      - name: Setup Theos
        uses: ./.github/actions/setup-theos

      - name: Install cyan and tbd
        run: |
          pipx install https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip
          wget --quiet --no-verbose "https://github.com/inoahdev/tbd/releases/download/2.2/tbd-mac" -O /usr/local/bin/tbd
          chmod +x /usr/local/bin/tbd

      - name: Build YTNoAds
        run: |
          cd YTNoAds
          echo "YTNOADS_VERSION=$(grep '^Version:' control | cut -d ' ' -f2)" >> $GITHUB_ENV
          make clean package DEBUG=0 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          mv packages/*.deb ${{ github.workspace }}/ytnoads.deb

      - name: Inject into IPA
        run: |
          cyan -i youtube.ipa -o YTNoAds_${{ env.YT_VERSION }}_v${{ env.YTNOADS_VERSION }}.ipa -uwef ytnoads.deb -n "YouTube" -b com.google.ios.youtube

      - name: Create a Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ytnoads-ipa${{ github.run_number }}
          name: YTNoAds_${{ env.YT_VERSION }}_v${{ env.YTNOADS_VERSION }} (${{ github.run_number }})
          files: YTNoAds_${{ env.YT_VERSION }}_v${{ env.YTNOADS_VERSION }}.ipa
          draft: true
